name: GitHub Deploy Test
on: [push]
  # workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  contents: read  # Required for checkout

jobs:
  test-oidc-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1 # Change if your resources are elsewhere

      - name: Identify AWS Identity
        run: aws sts get-caller-identity